server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.1.8:8888
    gateway:
      routes:
        - id: user-service # 路由标识，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否以/user开头，如果是则符合
        - id: order-service # 路由标识，必须唯一
          uri: lb://orderservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            # https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#gateway-request-predicates-factories
            # predicates-factories中包含各种路由断言工厂
            - Path=/order/** # 路径断言，判断路径是否以/user开头，如果是则符合
      #            - After=2035-01-20T17:42:47.789-07:00[America/Denver] # 异常--type=Not Found, status=404
      #          filters: # 局部过滤器
      #            - AddRequestHeader=Truth,Itcast is YYDS
      default-filters:
        - AddRequestHeader=Truth,Itcast is YYDS
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期